### ISSUE TITLE
The Python Library is not working on Windows

### ISSUE THREAD

**Issue by Bashamega** [merwin-asm/april#10]
**Describe the bug**
It is giving me that python is not installed but it is installed
**To Reproduce**
1. Get a Windows Computer
2. Open a terminal
3. Run `april -c file.apl`

**Expected behavior**
It should create the folder
**Screenshots**
![image](https://github.com/merwin-asm/april/assets/110662505/1c5d2bbd-2718-4b73-86d1-a9ffd945da24)

**Desktop (please complete the following information):**
Edition	Windows 11 Home
Version	22H2
Installed on	‎9/‎22/‎2022
OS build	22621.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

**Additional context**

**Comment by merwin-asm** [comment]
solved
